print("2021-1학기 시간표")
print("컴퓨터 공학과 2016244037 김광용")

print()
print(("=" * 100))
print("과목명\t\t\t요일\t\t교시\t\t담당교수님\t\t강의실")
print(("=" * 100))
print("종합프로젝트\t\t화\t\t1~2교시\t\t이현교수님\t\t인문409")
print("종합프로젝트\t\t목\t\t1~2교시\t\t이현교수님\t\t인문409")
print("네트워크실무\t\t화\t\t4~5교시\t\t김용우교수님\t인문436")
print("네트워크실무\t\t목\t\t6교시\t\t김용우교수님\t인문436")
print("파이썬프로그래밍\t\t화\t\t6교시\t\t배지혜교수님\t원화316")
print("파이썬프로그래밍\t\t목\t\t4~5교시\t\t배지혜교수님\t원화316")
print("인공지능\t\t\t금\t\t4~6교시\t\t양성민교수님\t인문436")
print(("=" * 100))
print()
print(("=" * 100))
print("구분\t월\t\t\t화\t\t수\t\t\t목\t\t\t금")
print(("=" * 100))
print("1교시\tx\t\t종합프로젝트\t\tx\t\t\t종합프로젝트\t\tx")
print("2교시\tx\t\t종합프로젝트\t\tx\t\t\t종합프로젝트\t\tx")
print("3교시\tx\t\tx\t\t\tx\t\t\tx\t\t\tx")
print("4교시\tx\t\t네트워크실무\t\tx\t\t\t파이썬프로그래밍\t\t인공지능")
print("5교시\tx\t\t네트워크실무\t\tx\t\t\t파이썬프로그래밍\t\t인공지능")
print("6교시\tx\t\t파이썬프로그래밍\t\tx\t\t\t네트워크실무\t\t인공지능")
